version: "3.8"

services:
  # Контейнер для api
  api:
    container_name: ${APP_NAME}-api
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - APP_NAME=${APP_NAME}
      - FASTAPI_ENV=${FASTAPI_ENV}
      - LOG_LEVEL=${LOG_LEVEL}
      - DB_URL=postgresql+asyncpg://${APP_NAME}:${SECRET_KEY}@localhost:5432/${APP_NAME}
      - API_BASE_URL=${API_BASE_URL}
      - SECRET_KEY=${SECRET_KEY}

  # Контейнер для postgres
  postgres:
    container_name: ${APP_NAME}-pg
    image: postgres:15
    environment:
      - POSTGRES_USER=${APP_NAME}
      - POSTGRES_PASSWORD=${SECRET_KEY}
      - POSTGRES_DB=${APP_NAME}
      - KEYCLOAK_DB=${APP_NAME}_keycloak
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  # Контейнер для keycloak
  keycloak:
    container_name: ${APP_NAME}-keycloak
    image: quay.io/keycloak/keycloak:26.4
    environment:
      - ENV_KC_DB=postgres
      - ENV_KC_DB_URL=postgresql+asyncpg://${APP_NAME}:${SECRET_KEY}@localhost:5432/${APP_NAME}_keycloak
      - ENV_KC_DB_USERNAME=${APP_NAME}
      - ENV_KC_DB_PASSWORD=${SECRET_KEY}
      - ENV_KC_HOSTNAME=localhost
      - KC_BOOTSTRAP_ADMIN_USERNAME=${APP_NAME}_admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=$SECRET_KEY

    ports:
      - "8080:8080"
    command: ["start-dev", "--http-port", "8080", "--log", "console"] 
    depends_on:
      - postgres


volumes:
  postgres_data: